from app import create_app
from app.extensions import db
from app.models.merchant import Merchant

def seed_merchants():
    app = create_app()
    
    with app.app_context():
        existing = Merchant.query.count()
        if existing > 0:
            print(f"Merchants already seeded ({existing} found). Skipping...")
            return
        
        merchants = [
            {
                'name': 'KFC',
                'category': 'Food and drink',
                'logo_url': '🍗',
                'discount_percentage': 10.0,
                'discount_description': '10% off all items (not valid for delivery)',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'KFC_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Subway',
                'category': 'Food and drink',
                'logo_url': '🥪',
                'discount_percentage': 10.0,
                'discount_description': '10% off all orders',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'SUB_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Starbucks',
                'category': 'Food and drink',
                'logo_url': '☕',
                'discount_percentage': 0.0,
                'discount_description': 'Special discounted price on Grande and Venti beverages',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'SBX_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Пица и Вино - Студентски град',
                'category': 'Food and drink',
                'logo_url': '🍕',
                'discount_percentage': 15.0,
                'discount_description': '15% off all pizza and 10% off wine',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'PIZZAVINO_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Jagermeister Online Shop',
                'category': 'Food and drink',
                'logo_url': '🍾',
                'discount_percentage': 10.0,
                'discount_description': '10% off via promo code',
                'online_domain': 'jagermeister.com',
                'online_url_patterns': ['jagermeister.com', 'shop.jagermeister.com'],
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'University Bookstore',
                'category': 'Shopping',
                'logo_url': '📚',
                'discount_percentage': 20.0,
                'discount_description': '20% off on textbooks',
                'online_domain': 'campusbooks.com',
                'online_url_patterns': ['campusbooks.com', 'universitybookstore.com'],
                'pos_merchant_id': 'BOOK_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'TechHub Electronics',
                'category': 'Shopping',
                'logo_url': '💻',
                'discount_percentage': 15.0,
                'discount_description': '15% off on laptops and accessories',
                'online_domain': 'techhub.com',
                'online_url_patterns': ['techhub.com', 'shop.techhub.com'],
                'pos_merchant_id': 'TECH_POS_001',
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': False
            },
            {
                'name': 'Nike',
                'category': 'Sport',
                'logo_url': '👟',
                'discount_percentage': 10.0,
                'discount_description': '10% off on all sportswear',
                'online_domain': 'nike.com',
                'online_url_patterns': ['nike.com', 'store.nike.com'],
                'pos_merchant_id': 'NIKE_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'FitZone Gym',
                'category': 'Sport',
                'logo_url': '🏋️',
                'discount_percentage': 25.0,
                'discount_description': '25% off on monthly membership',
                'online_domain': 'fitzone.com',
                'online_url_patterns': ['fitzone.com', 'join.fitzone.com'],
                'pos_merchant_id': 'FIT_POS_001',
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Under Armour',
                'category': 'Sport',
                'logo_url': '⚡',
                'discount_percentage': 20.0,
                'discount_description': '20% off',
                'online_domain': 'underarmour.com',
                'online_url_patterns': ['underarmour.com', 'www.underarmour.com'],
                'pos_merchant_id': 'UA_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Sofia Karting Ring',
                'category': 'Sport',
                'logo_url': '🏎️',
                'discount_percentage': 20.0,
                'discount_description': '20% off for a 10-minute session',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'KARTING_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'AREA 52 - Park',
                'category': 'Sport',
                'logo_url': '🎯',
                'discount_percentage': 15.0,
                'discount_description': '15% off activities',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'AREA52_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'GymBeam',
                'category': 'Sport',
                'logo_url': '💪',
                'discount_percentage': 5.0,
                'discount_description': '5% off',
                'online_domain': 'gymbeam.com',
                'online_url_patterns': ['gymbeam.com', 'www.gymbeam.com'],
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Fit City',
                'category': 'Sport',
                'logo_url': '🏃',
                'discount_percentage': 10.0,
                'discount_description': '10% off',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'FITCITY_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Coursera',
                'category': 'Study',
                'logo_url': '🎓',
                'discount_percentage': 30.0,
                'discount_description': '30% off on annual subscription',
                'online_domain': 'coursera.org',
                'online_url_patterns': ['coursera.org', 'www.coursera.org'],
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': False
            },
            {
                'name': 'JetBrains',
                'category': 'Study',
                'logo_url': '💻',
                'discount_percentage': 50.0,
                'discount_description': '50% off developer tools (or Free educational licenses)',
                'online_domain': 'jetbrains.com',
                'online_url_patterns': ['jetbrains.com', 'www.jetbrains.com', 'account.jetbrains.com'],
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Hacker4e Programming Academy for Children',
                'category': 'Study',
                'logo_url': '👨‍💻',
                'discount_percentage': 20.0,
                'discount_description': '20% off programming courses',
                'online_domain': 'hacker4e.com',
                'online_url_patterns': ['hacker4e.com'],
                'pos_merchant_id': 'HACKER4E_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Telerik Academy',
                'category': 'Study',
                'logo_url': '🎯',
                'discount_percentage': 5.0,
                'discount_description': '5% off training programs',
                'online_domain': 'telerikacademy.com',
                'online_url_patterns': ['telerikacademy.com', 'www.telerikacademy.com'],
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Kabinata',
                'category': 'Study',
                'logo_url': '📚',
                'discount_percentage': 10.0,
                'discount_description': '10% off online courses',
                'online_domain': 'kabinata.com',
                'online_url_patterns': ['kabinata.com'],
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Lingua Mundi Language Center',
                'category': 'Study',
                'logo_url': '🗣️',
                'discount_percentage': 10.0,
                'discount_description': '10% off group language courses',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'LINGUAMUNDI_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Spotify',
                'category': 'Entertainment',
                'logo_url': '🎵',
                'discount_percentage': 50.0,
                'discount_description': '50% off Student Premium',
                'online_domain': 'spotify.com',
                'online_url_patterns': ['spotify.com', 'accounts.spotify.com'],
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'CineWorld',
                'category': 'Entertainment',
                'logo_url': '🎬',
                'discount_percentage': 20.0,
                'discount_description': '20% off on movie tickets',
                'online_domain': 'cineworld.com',
                'online_url_patterns': ['cineworld.com', 'tickets.cineworld.com'],
                'pos_merchant_id': 'CINE_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': True,
                'requires_verification': False
            },
            {
                'name': 'City Museum',
                'category': 'Culture',
                'logo_url': '🏛️',
                'discount_percentage': 15.0,
                'discount_description': '15% off on entry tickets',
                'online_domain': 'citymuseum.org',
                'online_url_patterns': ['citymuseum.org', 'tickets.citymuseum.org'],
                'pos_merchant_id': 'MUS_POS_001',
                'nfc_enabled': False,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'H&M',
                'category': 'Shopping',
                'logo_url': '👕',
                'discount_percentage': 12.0,
                'discount_description': '12% off on clothing',
                'online_domain': 'hm.com',
                'online_url_patterns': ['hm.com', 'www2.hm.com'],
                'pos_merchant_id': 'HM_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': True,
                'requires_verification': False
            },
            {
                'name': 'Amazon Student',
                'category': 'Shopping',
                'logo_url': '📦',
                'discount_percentage': 10.0,
                'discount_description': '10% off + Prime benefits',
                'online_domain': 'amazon.com',
                'online_url_patterns': ['amazon.com', 'www.amazon.com', 'smile.amazon.com'],
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Elephant Bookstore',
                'category': 'Shopping',
                'logo_url': '📖',
                'discount_percentage': 20.0,
                'discount_description': '20% off with a promo code',
                'online_domain': 'elephantbookstore.com',
                'online_url_patterns': ['elephantbookstore.com'],
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Bookspace',
                'category': 'Shopping',
                'logo_url': '📚',
                'discount_percentage': 10.0,
                'discount_description': '10% off at the online bookstore',
                'online_domain': 'bookspace.bg',
                'online_url_patterns': ['bookspace.bg', 'www.bookspace.bg'],
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Lenovo Exclusive Store',
                'category': 'Shopping',
                'logo_url': '💻',
                'discount_percentage': 5.0,
                'discount_description': '5% off all Lenovo products',
                'online_domain': 'lenovo.com',
                'online_url_patterns': ['lenovo.com', 'www.lenovo.com'],
                'pos_merchant_id': 'LENOVO_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Grand Optics',
                'category': 'Shopping',
                'logo_url': '👓',
                'discount_percentage': 30.0,
                'discount_description': 'Up to 30% off',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'GRANDOPTICS_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Sport Box',
                'category': 'Shopping',
                'logo_url': '⚽',
                'discount_percentage': 10.0,
                'discount_description': '10% off products',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'SPORTBOX_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Campus Transit',
                'category': 'Travel',
                'logo_url': '🚌',
                'discount_percentage': 25.0,
                'discount_description': '25% off on monthly bus pass',
                'online_domain': 'campustransit.com',
                'online_url_patterns': ['campustransit.com', 'tickets.campustransit.com'],
                'pos_merchant_id': 'BUS_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Bulgarian State Railways',
                'category': 'Travel',
                'logo_url': '🚂',
                'discount_percentage': 50.0,
                'discount_description': '50% off train tickets',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'BDZ_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Usit Colours',
                'category': 'Travel',
                'logo_url': '✈️',
                'discount_percentage': 50.0,
                'discount_description': '50% off the service fee for plane tickets and 5% off hotels',
                'online_domain': 'usitcolours.bg',
                'online_url_patterns': ['usitcolours.bg', 'www.usitcolours.bg'],
                'pos_merchant_id': 'USIT_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'FlixBUS',
                'category': 'Travel',
                'logo_url': '🚍',
                'discount_percentage': 15.0,
                'discount_description': '15% off bus tickets',
                'online_domain': 'flixbus.com',
                'online_url_patterns': ['flixbus.com', 'www.flixbus.com'],
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Kiwi',
                'category': 'Travel',
                'logo_url': '🥝',
                'discount_percentage': 0.0,
                'discount_description': '20 BGN off flights over 200 BGN',
                'online_domain': 'kiwi.com',
                'online_url_patterns': ['kiwi.com', 'www.kiwi.com'],
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'QATAR Airways',
                'category': 'Travel',
                'logo_url': '🛫',
                'discount_percentage': 20.0,
                'discount_description': 'Up to 20% off as a member of the Student Club',
                'online_domain': 'qatarairways.com',
                'online_url_patterns': ['qatarairways.com', 'www.qatarairways.com'],
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Хотел Kitchen59',
                'category': 'Accommodation',
                'logo_url': '🏨',
                'discount_percentage': 15.0,
                'discount_description': '15% off all room types',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'KITCHEN59_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'хотел Перелик 5* - Пампорово',
                'category': 'Accommodation',
                'logo_url': '🏨',
                'discount_percentage': 30.0,
                'discount_description': '30% off accommodation',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'PERELIK_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Хотел Балканско Бижу',
                'category': 'Accommodation',
                'logo_url': '🏨',
                'discount_percentage': 15.0,
                'discount_description': '15% off accommodation',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'BALKANSKO_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Хотел Фламинго - Пловдив',
                'category': 'Accommodation',
                'logo_url': '🏨',
                'discount_percentage': 10.0,
                'discount_description': '10% off',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'FLAMINGO_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Homestay',
                'category': 'Accommodation',
                'logo_url': '🏠',
                'discount_percentage': 50.0,
                'discount_description': '50% off the online booking fee',
                'online_domain': 'homestay.com',
                'online_url_patterns': ['homestay.com', 'book.homestay.com'],
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Historical Park',
                'category': 'Culture',
                'logo_url': '🏛️',
                'discount_percentage': 10.0,
                'discount_description': '10% off entry and activities (archery, horse riding)',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'HISTPARK_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Museum of Illusions',
                'category': 'Culture',
                'logo_url': '🎨',
                'discount_percentage': 19.0,
                'discount_description': 'Discounted entry price (17 BGN instead of 21 BGN)',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'ILLUSIONS_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Castle "IN LOVE WITH THE WIND" Ravadinovo',
                'category': 'Culture',
                'logo_url': '🏰',
                'discount_percentage': 25.0,
                'discount_description': '25% off entry',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'CASTLE_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Sofia Opera and Ballet',
                'category': 'Culture',
                'logo_url': '🎭',
                'discount_percentage': 20.0,
                'discount_description': '20% off tickets',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'OPERA_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Regional Archaeological Museum - Plovdiv',
                'category': 'Culture',
                'logo_url': '🏺',
                'discount_percentage': 0.0,
                'discount_description': 'Special student price (2 BGN)',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'ARCHMUSEUM_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'GIFT TUBE',
                'category': 'Entertainment',
                'logo_url': '🎁',
                'discount_percentage': 7.0,
                'discount_description': '7% off vouchers for experiences',
                'online_domain': 'gifttube.com',
                'online_url_patterns': ['gifttube.com'],
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Funky Monkeys - Escape HUB',
                'category': 'Entertainment',
                'logo_url': '🐵',
                'discount_percentage': 5.0,
                'discount_description': '5% off escape rooms',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'FUNKYMONKEYS_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'ALCOHOPOLY',
                'category': 'Entertainment',
                'logo_url': '🎲',
                'discount_percentage': 10.0,
                'discount_description': '10% off the board game',
                'online_domain': 'alcohopoly.com',
                'online_url_patterns': ['alcohopoly.com'],
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': True,
                'requires_verification': True
            },
            {
                'name': 'Escape Project - Illusion',
                'category': 'Entertainment',
                'logo_url': '🔐',
                'discount_percentage': 10.0,
                'discount_description': '10% off',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'ESCAPEPROJECT_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'CLWD (EXE Club)',
                'category': 'Entertainment',
                'logo_url': '🎉',
                'discount_percentage': 0.0,
                'discount_description': 'Free entry on specific nights (e.g., Thursdays)',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'CLWD_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Volt Premium Taxi',
                'category': 'Services',
                'logo_url': '🚖',
                'discount_percentage': 10.0,
                'discount_description': '10% off rides',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'VOLT_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Diana Tires',
                'category': 'Services',
                'logo_url': '🚗',
                'discount_percentage': 33.0,
                'discount_description': '33% off tires and 25% off mounting/balancing',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'DIANA_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Kandilarov Laboratory',
                'category': 'Services',
                'logo_url': '🧪',
                'discount_percentage': 10.0,
                'discount_description': '10% off lab tests',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'KANDILAROV_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'MANIA PRINT',
                'category': 'Services',
                'logo_url': '🖨️',
                'discount_percentage': 0.0,
                'discount_description': 'Preferential prices on printing services',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'MANIAPRINT_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'SALT ME - солни стаи',
                'category': 'Services',
                'logo_url': '💆',
                'discount_percentage': 10.0,
                'discount_description': '10% off services (Mon-Wed)',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'SALTME_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'OMV Gas Stations',
                'category': 'Other',
                'logo_url': '⛽',
                'discount_percentage': 0.0,
                'discount_description': 'Special barcode discounts via the MyISIC app',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'OMV_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Mastercard Day Cashback',
                'category': 'Other',
                'logo_url': '💳',
                'discount_percentage': 10.0,
                'discount_description': '10% cashback on the first day of each month',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Imotiko Real Estate',
                'category': 'Other',
                'logo_url': '🏢',
                'discount_percentage': 10.0,
                'discount_description': '10% off the commission',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': None,
                'nfc_enabled': False,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Enigma Aesthetic Center',
                'category': 'Other',
                'logo_url': '💅',
                'discount_percentage': 10.0,
                'discount_description': '10% off all therapies',
                'online_domain': None,
                'online_url_patterns': None,
                'pos_merchant_id': 'ENIGMA_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': False,
                'requires_verification': True
            },
            {
                'name': 'Sexwell',
                'category': 'Other',
                'logo_url': '🛍️',
                'discount_percentage': 10.0,
                'discount_description': '10% off in-store and online',
                'online_domain': 'sexwell.bg',
                'online_url_patterns': ['sexwell.bg', 'www.sexwell.bg'],
                'pos_merchant_id': 'SEXWELL_POS_001',
                'nfc_enabled': True,
                'auto_apply_online': True,
                'requires_verification': True
            }
        ]
        
        for merchant_data in merchants:
            merchant = Merchant(**merchant_data)
            db.session.add(merchant)
        
        db.session.commit()
        print(f"✅ Successfully seeded {len(merchants)} merchants!")

if __name__ == '__main__':
    seed_merchants()
