"""Add indexes to foreign keys and frequently queried columns

Revision ID: 748f170551f2
Revises: d16c8d920bc4
Create Date: 2025-11-11 13:51:40.244579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748f170551f2'
down_revision = 'd16c8d920bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goals_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('loan_repayments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loan_repayments_loan_id'), ['loan_id'], unique=False)

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_borrower_id'), ['borrower_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_lender_id'), ['lender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_status'), ['status'], unique=False)

    with op.batch_alter_table('marketplace_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_listings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_listings_is_available'), ['is_available'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_listings_is_sold'), ['is_sold'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_listings_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_listings_university'), ['university'], unique=False)

    with op.batch_alter_table('marketplace_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marketplace_orders_buyer_id'), ['buyer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_orders_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_marketplace_orders_status'), ['status'], unique=False)

    with op.batch_alter_table('savings_pockets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_savings_pockets_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_card_id'), ['card_id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_card_id'), ['card_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_sender_id'), ['sender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_transaction_type'), ['transaction_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('virtual_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_virtual_cards_card_purpose'), ['card_purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_virtual_cards_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_virtual_cards_user_id'))
        batch_op.drop_index(batch_op.f('ix_virtual_cards_card_purpose'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_transaction_type'))
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_sender_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_card_id'))

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_card_id'))

    with op.batch_alter_table('savings_pockets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_savings_pockets_user_id'))

    with op.batch_alter_table('marketplace_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_orders_status'))
        batch_op.drop_index(batch_op.f('ix_marketplace_orders_listing_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_orders_buyer_id'))

    with op.batch_alter_table('marketplace_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marketplace_listings_university'))
        batch_op.drop_index(batch_op.f('ix_marketplace_listings_seller_id'))
        batch_op.drop_index(batch_op.f('ix_marketplace_listings_is_sold'))
        batch_op.drop_index(batch_op.f('ix_marketplace_listings_is_available'))
        batch_op.drop_index(batch_op.f('ix_marketplace_listings_category'))

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_status'))
        batch_op.drop_index(batch_op.f('ix_loans_lender_id'))
        batch_op.drop_index(batch_op.f('ix_loans_borrower_id'))

    with op.batch_alter_table('loan_repayments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loan_repayments_loan_id'))

    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goals_user_id'))

    # ### end Alembic commands ###
