"""Add cancelled_at to loans table

Revision ID: d16c8d920bc4
Revises: b5a1174e83b3
Create Date: 2025-11-09 08:54:35.971838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16c8d920bc4'
down_revision = 'b5a1174e83b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('cancelled_at')

    # ### end Alembic commands ###
